#!/bin/bash
cp 7.png c0r00.png
cp 49.png c1r00.png
cp 11.png c0r01.png
cp 121.png c1r01.png
cp 3p1sq2.png c2r00.png
cp 11p6sq2.png c3r00.png
cp 3m1sq2.png c2r01.png
cp 11m6sq2.png c3r01.png
convert c0r*.png -append c0.png
convert c1r*.png -append c1.png
convert c0.png c1.png +append c4.png
convert c2r*.png -append c2.png
convert c3r*.png -append c3.png
convert c2.png c3.png +append c5.png
convert c4.png c5.png -append sprite.png
rm c*.png
